//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFH.NetDS.WebServices.CodingSession.Client.UserClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/BFH.NetDS.WebServices.CodingSession.Servi" +
        "ce")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BFH.NetDS.WebServices.CodingSession.Client.UserClient.User))]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accountName {
            get {
                return this.accountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.accountNameField, value) != true)) {
                    this.accountNameField = value;
                    this.RaisePropertyChanged("accountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/BFH.NetDS.WebServices.CodingSession.Servi" +
        "ce")]
    [System.SerializableAttribute()]
    public partial class User : BFH.NetDS.WebServices.CodingSession.Client.UserClient.UserInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> lastLogonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> lastLogon {
            get {
                return this.lastLogonField;
            }
            set {
                if ((this.lastLogonField.Equals(value) != true)) {
                    this.lastLogonField = value;
                    this.RaisePropertyChanged("lastLogon");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserClient.UserService")]
    public interface UserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/fetchUsers", ReplyAction="http://tempuri.org/UserService/fetchUsersResponse")]
        BFH.NetDS.WebServices.CodingSession.Client.UserClient.UserInfo[] fetchUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/fetchUsers", ReplyAction="http://tempuri.org/UserService/fetchUsersResponse")]
        System.Threading.Tasks.Task<BFH.NetDS.WebServices.CodingSession.Client.UserClient.UserInfo[]> fetchUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/fetchUser", ReplyAction="http://tempuri.org/UserService/fetchUserResponse")]
        BFH.NetDS.WebServices.CodingSession.Client.UserClient.User fetchUser(string accountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/fetchUser", ReplyAction="http://tempuri.org/UserService/fetchUserResponse")]
        System.Threading.Tasks.Task<BFH.NetDS.WebServices.CodingSession.Client.UserClient.User> fetchUserAsync(string accountName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceChannel : BFH.NetDS.WebServices.CodingSession.Client.UserClient.UserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<BFH.NetDS.WebServices.CodingSession.Client.UserClient.UserService>, BFH.NetDS.WebServices.CodingSession.Client.UserClient.UserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BFH.NetDS.WebServices.CodingSession.Client.UserClient.UserInfo[] fetchUsers() {
            return base.Channel.fetchUsers();
        }
        
        public System.Threading.Tasks.Task<BFH.NetDS.WebServices.CodingSession.Client.UserClient.UserInfo[]> fetchUsersAsync() {
            return base.Channel.fetchUsersAsync();
        }
        
        public BFH.NetDS.WebServices.CodingSession.Client.UserClient.User fetchUser(string accountName) {
            return base.Channel.fetchUser(accountName);
        }
        
        public System.Threading.Tasks.Task<BFH.NetDS.WebServices.CodingSession.Client.UserClient.User> fetchUserAsync(string accountName) {
            return base.Channel.fetchUserAsync(accountName);
        }
    }
}
