//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFH.NetDS.WebServices.ControlStation.BFH.NetDS.WebServices.Terminal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Statistics", Namespace="http://schemas.datacontract.org/2004/07/BFH.NetDS.WebServices.Terminal")]
    [System.SerializableAttribute()]
    public partial class Statistics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberOfTimeStampsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberOfUniqueUsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberOfTimeStamps {
            get {
                return this.numberOfTimeStampsField;
            }
            set {
                if ((this.numberOfTimeStampsField.Equals(value) != true)) {
                    this.numberOfTimeStampsField = value;
                    this.RaisePropertyChanged("numberOfTimeStamps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberOfUniqueUsers {
            get {
                return this.numberOfUniqueUsersField;
            }
            set {
                if ((this.numberOfUniqueUsersField.Equals(value) != true)) {
                    this.numberOfUniqueUsersField = value;
                    this.RaisePropertyChanged("numberOfUniqueUsers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BFH.NetDS.WebServices.Terminal.TerminalService")]
    public interface TerminalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TerminalService/SetNews", ReplyAction="http://tempuri.org/TerminalService/SetNewsResponse")]
        void SetNews(string news);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TerminalService/SetNews", ReplyAction="http://tempuri.org/TerminalService/SetNewsResponse")]
        System.Threading.Tasks.Task SetNewsAsync(string news);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TerminalService/GetStatistics", ReplyAction="http://tempuri.org/TerminalService/GetStatisticsResponse")]
        BFH.NetDS.WebServices.ControlStation.BFH.NetDS.WebServices.Terminal.Statistics GetStatistics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TerminalService/GetStatistics", ReplyAction="http://tempuri.org/TerminalService/GetStatisticsResponse")]
        System.Threading.Tasks.Task<BFH.NetDS.WebServices.ControlStation.BFH.NetDS.WebServices.Terminal.Statistics> GetStatisticsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TerminalServiceChannel : BFH.NetDS.WebServices.ControlStation.BFH.NetDS.WebServices.Terminal.TerminalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TerminalServiceClient : System.ServiceModel.ClientBase<BFH.NetDS.WebServices.ControlStation.BFH.NetDS.WebServices.Terminal.TerminalService>, BFH.NetDS.WebServices.ControlStation.BFH.NetDS.WebServices.Terminal.TerminalService {
        
        public TerminalServiceClient() {
        }
        
        public TerminalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TerminalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetNews(string news) {
            base.Channel.SetNews(news);
        }
        
        public System.Threading.Tasks.Task SetNewsAsync(string news) {
            return base.Channel.SetNewsAsync(news);
        }
        
        public BFH.NetDS.WebServices.ControlStation.BFH.NetDS.WebServices.Terminal.Statistics GetStatistics() {
            return base.Channel.GetStatistics();
        }
        
        public System.Threading.Tasks.Task<BFH.NetDS.WebServices.ControlStation.BFH.NetDS.WebServices.Terminal.Statistics> GetStatisticsAsync() {
            return base.Channel.GetStatisticsAsync();
        }
    }
}
